config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from rest_framework.documentation import include_docs_urls

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Duty API for todo app",
        default_version="v1",
        description="This is a test documentation for todo app",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("duties/", include("duties.urls")),
    path("accounts/", include("accounts.urls")),
    path("403/", TemplateView.as_view(template_name="403.html")),
    path("api-auth/", include("rest_framework.urls")),
    # document urls
    path("api/", TemplateView.as_view(template_name="doc.html"), name="api-docs"),
    path("api-docs/", include_docs_urls(title="api sample doc")),
    path(
        "swagger/api.json", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

duties/api/v1/urls.py
from rest_framework.routers import DefaultRouter
from . import views
from django.urls import path

app_name = "api-v1"

""" create a router for duty urls"""
router = DefaultRouter()
router.register("duty", views.DutyModelViewSet, basename="duty")
urlpatterns = router.urls

urlpatterns += [
    # weather caching endpoint
    path("weather/", views.WeatherCacheApiView.as_view(), name="weather"),
]

templates/_base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block page_title %} {% endblock page_title %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'duty_list' %}">My duties</a>
                <a class="nav-link active" href="{% url 'duty_create' %}">Create a new duty |</a> 
                <a class="nav-link active" href="{% url 'api-v1:api-root' %}">API Section |</a>
                <a class="nav-link active" href="{% url 'api-docs' %}">API documentation |</a>
                <a class="nav-link active" href="{% url 'api-v1:weather' %}">Weather api</a>


            </div>
        </div>
        {% if user.is_authenticated %}
        <div class="mx-2 text-white">Welcome {{user.email}} | <a class="mx-2 text-white text-decoration-none" href="{% url 'logout' %}">Logout</a> | <a class="mx-2 text-white text-decoration-none" href="{%url 'password_change' %}">Change Password</a></div>
        {% else %}
        <div class="mx-2 text-white"><a class="mx-2 text-white text-decoration-none" href="{% url 'login' %}">Login</a> | <a class="mx-2 text-white text-decoration-none" href="{% url 'signup' %}">Signup</a> | <a class="mx-2 text-white text-decoration-none" href="{% url 'password_reset'%}">Forget Password</a></div>
        {% endif %}

    </div>
</nav>

<div class="container-fluid bg-info">
    <div class="row py-3">
        <div class="col-md-8 col-md-10 mx-auto">
            <h3 class="my-4 mt-3 text-white">Welcome to ToDo app created by Django</h3>
            <p class="text-light">With this app you can define duties for yourself and specify a deadline for them!</p>
        </div>
    </div>
</div>
<div class="container mt-3">
    {% block content %}
    
    {% endblock content %}

</div>


<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>
</html>

templates/doc.html
{% extends '_base.html' %}

{% block page_title %}
API documentation

{% endblock page_title %}

{% block content %}
<div class="container mt-3 " style="width: 60rem;">
    <h1>You can see three types of api document api here!</h1>
    <br><br>
    <h4>
        In order to see a simple api document using restframework, <a class="text-decoration-none"href="/api-docs">click here</a>

    </h4>
    <br>
    <h4>
        In order to see swagger documentation , <a class="text-decoration-none"href="{% url 'schema-swagger-ui' %}">click here</a>

    </h4>
    <br>
    <h4>
        In order to see redoc documentation , <a class="text-decoration-none"href="{% url 'schema-redoc' %}">click here</a>

    </h4>
    <br>
    <h4>
        In order to download swager json doc file , <a class="text-decoration-none"href="{% url 'schema-json' %}">click here</a>

    </h4>



 
</div>


{% endblock content %}

templates/home.html
{% extends '_base.html' %}

{% block page_title %}
Home

{% endblock page_title %}

{% block content %}
<div class="container mt-3 " style="width: 40rem;">
    

    {% if user.is_authenticated %}
    <h3>You can see your todo list <a class="text-decoration-none" href="{% url 'duty_list' %}">here</a></h3>
    {% else %}
    <h3>In order to use this app, you should first <a class="text-decoration-none" href="{% url 'login' %}">login</a></h3>
    <h3>Don't have an account. <a class="text-decoration-none" href="{% url 'signup' %}">Signup</a> now!</h3>
    <h3>Forget password?? ooops! click <a class="text-decoration-none" href="{% url 'password_reset'%}">here!!</a></h3>
    {% endif %}
</div>


{% endblock content %}